// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwybtY-Cu3iY9EzIEtwj9VBH79jlw1UnU',
    appId: '1:636911593810:web:35f0122ea379bd1012b28b',
    messagingSenderId: '636911593810',
    projectId: 'chat-app-23306',
    authDomain: 'chat-app-23306.firebaseapp.com',
    storageBucket: 'chat-app-23306.firebasestorage.app',
    measurementId: 'G-256N3CF4T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaodCzPZQIuThPSjedL8ekVxXDW3diqa8',
    appId: '1:636911593810:android:9f4535be6b3c64f912b28b',
    messagingSenderId: '636911593810',
    projectId: 'chat-app-23306',
    storageBucket: 'chat-app-23306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBd_6heokoxBcpXDdPLA7Ntfm0HaCnBio',
    appId: '1:636911593810:ios:230cf2a451c348bd12b28b',
    messagingSenderId: '636911593810',
    projectId: 'chat-app-23306',
    storageBucket: 'chat-app-23306.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBd_6heokoxBcpXDdPLA7Ntfm0HaCnBio',
    appId: '1:636911593810:ios:230cf2a451c348bd12b28b',
    messagingSenderId: '636911593810',
    projectId: 'chat-app-23306',
    storageBucket: 'chat-app-23306.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwybtY-Cu3iY9EzIEtwj9VBH79jlw1UnU',
    appId: '1:636911593810:web:53f481515523604512b28b',
    messagingSenderId: '636911593810',
    projectId: 'chat-app-23306',
    authDomain: 'chat-app-23306.firebaseapp.com',
    storageBucket: 'chat-app-23306.firebasestorage.app',
    measurementId: 'G-Q65BBPJYPQ',
  );
}
